name: ss99
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: "3.6.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  aligned_dialog: ^0.0.6
  auto_size_text: ^3.0.0
  carousel_slider: ^5.0.0
  cloud_firestore: ^5.5.1
  cloud_functions: ^5.1.5
  collection: ^1.19.0
  csslib: ^1.0.2
  dropdown_button2: ^2.3.9
  easy_debounce: ^2.0.1
  equatable: ^2.0.5
  file_picker: ^8.1.2
  firebase_analytics: ^11.4.0
  firebase_auth: ^5.4.0
  firebase_core: ^3.10.0
  firebase_messaging: ^15.2.0
  firebase_performance: ^0.10.1
  firebase_storage: ^12.4.0
  flutter_animate: ^4.5.2
  flutter_cache_manager: ^3.4.1
  flutter_facebook_auth: ^7.1.1
  flutter_native_splash: ^2.4.4
  flutter_plugin_android_lifecycle: ^2.0.20
  flutter_rating_bar: ^4.0.1
  flutter_slidable: ^3.1.2
  flutter_spinkit: ^5.2.1
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.11
  fluttertoast: ^8.2.2
  font_awesome_flutter: ^10.7.3
  from_css_color: ^2.0.0
  go_router: ^14.6.3
  google_fonts: ^6.2.0
  google_sign_in: ^6.2.1
  html: ^0.15.5
  http: ^1.2.2
  image_picker: ^1.1.2
  intl: ^0.19.0
  js: ^0.6.7
  json_path: ^0.7.2
  mime_type: ^1.0.0
  package_info_plus: ^8.1.0
  page_transition: ^2.2.0
  path_provider: ^2.1.5
  photo_view: ^0.15.0
  plugin_platform_interface: ^2.1.8
  provider: ^6.1.2
  rxdart: ^0.28.0
  share_plus: ^10.1.4
  shared_preferences: ^2.3.5
  sign_in_with_apple: ^6.1.4
  sqflite: ^2.3.4+1
  sqflite_common: ^2.5.4+6
  stream_transform: ^2.1.0
  substring_highlight: ^1.0.33
  text_search: ^1.0.2
  timeago: ^3.6.1
  universal_io: ^2.2.2
  url_launcher: ^6.3.0
  video_player: ^2.9.2
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  razorpay_web: ^2.0.2


#dependency_overrides:
#  http: 1.2.2
#  package_info_plus: 8.0.2
#  uuid: ^4.0.0
#  win32: 5.5.1

dev_dependencies:
  flutter_launcher_icons: 0.13.1
  flutter_lints: 4.0.0
  lints: 4.0.0
  flutter_test:
    sdk: flutter


flutter_launcher_icons:
  android: 'launcher_icon'
  ios: true
  web:
    generate: true
  image_path: 'assets/images/app_launcher_icon.jpg'
  adaptive_icon_background: '#ffffff'
  adaptive_icon_foreground: 'assets/images/adaptive_foreground_icon.png'


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/fonts/
    - assets/images/
    - assets/videos/
    - assets/audios/
    - assets/rive_animations/
    - assets/pdfs/
    - assets/jsons/

  fonts:
    - family: 'neue font'
      fonts:
        - asset: assets/fonts/HelveticaNeueLight.otf
          weight: 300

    - family: Icomoon
      fonts:
        - asset: assets/fonts/icomoon.ttf


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

